baseURL = "https://hugorocaproyectos.js.org/"
languageCode = "es-PE"
title = "Hugo Roca Proyectos"
summerization = "html_firstparagraph"
paginate = 9 
theme = "bleak"
disqusShortname = "hugorocaproyectos"
contentdir      = "content"
datadir         = "data"
layoutdir       = "layouts"
publishdir      = "docs"

[permalinks]
  post = "/post/:year/:month/:day/:slug"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Warning Keys are case sensitives
  Subtitle = "Sistemas, información, "
  description = "Alter Way une autre idée du web, open source inside, design, build, run train."
  cover = "/images/oss.jpg"

  # Google analytics
  ga = "UA-125594168-1"
  twitter = "xxxxx"
  github = "hugoroca"
  facebook = "xxxxx"
  linkedin = "xxxxx"
  gplus = ""
  logo = "/images/logo.png"

[author]
  FirstName = "Hugo"
  LastName = "Roca"
  Gender = "male"
  UserName = "hugo.roca"
  Image = "/images/hugo.jpeg"
  Website = "https://hugoroca.github.io"

[[menu.main]]
  name = "Acerca de mí"
  url = "https://hugoroca.github.io/"

[[menu.main]]
  name = "Tags"
  url = "/tags"